x = input("Enter num1: ")
y = input("Enter num2: ")             
a = float(x)-float(y)
b = float(x)+float(y)
c = float(x)*float(y)
d = float(x)**float(y)
e = float(x)/float(y)
print("subtraction",a)
print("Sum",b)
print("Product",c)
print("Power",d)
print("Quotient",e)