x = input("Enter num1: ")
y = input("Enter num2: ")  
z = input("Enter num3: ")  
a = float(x)-float(y)-float(z)
b = float(x)+float(y)+float(z)
c = float(x)*float(y)*float(z)
d = float(x)**float(y)**float(z)
e = float(x)/float(y)/float(z)
print("subtraction",a)
print("Sum",b)
print("Product",c)
print("Power",d)
print("Quotient",e)
